run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/nereo-ar/backend

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 10
